package com.csye6225.spring2020.courseservice.datamodel;

//import javax.xml.bind.annotation.XmlRootElement;

//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class Professor {
	private String alias;
	private String firstName;
	private String lastName;
	private String department;
	private String joiningDate;
	private String email;

	public Professor() {

	}

	public Professor(String alias, String firstName, String lastName, String department, String joiningDate, String email) {
		this.alias = alias;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
		this.joiningDate = joiningDate;
		this.email = email;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getAlias() {
		return alias;
	}

	public String getJoiningDate() {
		return joiningDate;
	}

	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail() {
		this.email = String.format("%s@example.com", getAlias());
	}

	@Override
	public String toString() {
		return "alias=" + getAlias() + ", firstName=" + getFirstName() + ", department=" + getDepartment()
				+ ", joiningDate=" + getJoiningDate() + ", email=" + getEmail();
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
}
